### ISSUE TITLE
There should not be color preview beside some jQuery id selectors

### ISSUE THREAD

**Issue by humphreygao** [junichi11/netbeans-color-codes-preview#40]
I activated color preview in HTML files using the regex :
`^text/(x-)?(css|less|sass|scss|.*xml|.*html)$`

and accidentally found this:
![jquery id selector in HTML](https://user-images.githubusercontent.com/52394598/76124633-17adfb80-6036-11ea-8e78-e4c89ac66de9.png)

**Environments**
 - OS: Windows 10
 - NetBeans Version: 11.3
 - Plugin Version: 0.12.4

**Comment by junichi11** [comment]
I know this problem (https://github.com/junichi11/netbeans-color-codes-preview#note-2). However,
I'm not going to fix this at the moment.

This feature is called many times. I don't want to add conditions as much as possible because I would like to avoid that the performance becomes bad. So, just checking hex code currently.
